# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Murphy
email: tim@timmurphy.it
description: > # this means to ignore newlines until "baseurl:"
  Tim Murphy is an entrepreneur, developer, blogger, screencaster, croquet player and husband. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timmurphy.it" # the base hostname & protocol for your site
twitter_username: timpmurphy
github_username:  Tim Murphy

# Build settings
markdown: kramdown
